//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPOLOGIA
    {
        public int CO_TIPOLOGIA { get; set; }
        public string NO_TIPOLOGIA { get; set; }
        public string TIPO_HABITACAO { get; set; }
        public int AREA_PRIVATIVA { get; set; }
        public string RENDA_FAM { get; set; }
        public Nullable<decimal> VALOR_INICIAL { get; set; }
        public Nullable<decimal> VALOR_FINAL { get; set; }
    }
}
